on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate content
        run: |
          CONTENT=$(cat << EOF
          # For now ($(date +'%l:%M %p on %v')) I am Daniel Pustotin
          ## Reach me at [@heartsker](https://t.me/heartsker)
          ## Or email me - daniel.pustotin@gmail.com
          EOF
          )
          echo "CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: content
        
      - name: Update README.md
        run: echo "${{ env.CONTENT }}" > README.md
        
      - name: Commit updates
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name heartsker
          git config user.email heartsker@gmail.com
          git add .
          git commit -m "Updated README.md $(date +'at %l:%M %p on %v')"
          git push
          fi
